server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.23.132:3306/callnumber?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.mrliu.bean